Revert "jQuery, upgrade to 3.4.1, keep 3.2.1 on disk for older third party plugins and disable jquery-migrations while herre."
-- seems to be for later, dashboard dies with "Uncaught TypeError: e.indexOf is not a function .... "

This reverts commit f769065c66260a5e68ef2dd78d8b95a63bd0b443.