Firewall/Alias - fix traceback (wrong return type on empty response)
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/filter/update_tables.py", line 85, in <module>
    alias_content = alias.cached() if use_cached(alias_name) else alias.resolve()
  File "/usr/local/opnsense/scripts/filter/lib/alias/__init__.py", line 180, in resolve
    for address in address_parser.iter_addresses(item):
  File "/usr/local/opnsense/scripts/filter/lib/alias/auth.py", line 71, in iter_addresses
    self._update()
  File "/usr/local/opnsense/scripts/filter/lib/alias/auth.py", line 53, in _update
    for server in ovpn_status.get('server', None):
TypeError: 'NoneType' object is not iterable

(cherry picked from commit 1cac50b4ac4200acba7f0fbc7867cd17849d1097)