mvc: remove some stray code in api handling for https://github.com/opnsense/core/issues/6389.
Fixes:

   Error: Call to undefined method OPNsense\Mvc\Dispatcher::getParams() in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:284

dispatch errors are handled inside the Dispatch->resolve() now

(cherry picked from commit d7d016f400fbcc30c29973b1315db12055cce0f7)