System: Gateways: Configuration - ensure proper types are emitted in searchGatewayAction() when configd action fails.
should prevent hard failures like:

TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /usr/local/opnsense/mvc/app/controllers/OPNsense/Routing/Api/SettingsController.php:122 Stack trace: #0
(cherry picked from commit a19a72cda8a9eb82ea4646f3b2a31f374e760a8c)