unbound: remove recently recovered optimization, because...
error: setsockopt(..., SO_RCVBUF, ...) failed: No buffer space available
(cherry picked from commit 9d392294ab67be36f4c1c5707a73727d34094e31)