HTML Compliance - Lobby: License
Error: Stray end tag span.

Error: No p element in scope but a p end tag seen.
The ordered list makes paragraph tag unnecessary.

(cherry picked from commit e66eb970b92357b82d8add06057fb07af2ef6690)