Revert "jQuery, upgrade to 3.4.1, keep 3.2.1 on disk for older third party plugins and disable jquery-migrations while herre."
-- seems to be for later, dashboard dies with "Uncaught TypeError: e.indexOf is not a function .... "

This reverts commit 91fc7e7665cb83d630429dc3b22c3733af058013.